name = "backend"
compatibility_date = "2023-12-01"

# [vars]
# MY_VARIABLE = "production_value"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""


node_compat = true
[vars]
JWT_SECRET = "mySuperDooperSecret"
DIRECT_URL   = "postgresql://shashwat.saxena612:VzM1fdULsSq7@ep-proud-paper-a5eshi9m.us-east-2.aws.neon.tech/neondb?sslmode=require"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNmI4N2JmMTYtNzc2Mi00ZTEzLTk5NzktNTNiNjdjZjY0MmNjIiwidGVuYW50X2lkIjoiNzdiOTFiYzVjNzY1Y2QyNTAwOTY2ODEwMDAwMGY4N2UyNGFmZDg5NTkxNmExMDFkY2E1ZjRmMjc2MjkwYmY3YSIsImludGVybmFsX3NlY3JldCI6IjY3MjU2NGE1LTYzMjctNDBlZC04MGNlLTY4OTkyZWUxNWRhMiJ9.OsM55GpS5GRIPCGyd9lYSqFqlee6d7RUPQ1YL80-05Y"
